language: python

matrix:
  include:
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
      dist: xenial
      sudo: true

install:
- travis_retry pip install pipenv
- travis_retry pipenv install --dev --three
- travis_retry python ./setup.py install

script:
  pipenv run py.test --cov=twempest --cov=tests --cov-report=term-missing --cov-fail-under=80 --flake8 -W ignore::DeprecationWarning twempest tests

after_success:
- bash <(curl -s https://codecov.io/bash)
