language: python

matrix:
  include:
    # Use the built in venv for linux builds
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    # Use generic language for osx
    - os: osx
      language: generic

# Perform the manual steps on osx to install python3 and activate venv
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate ; fi

install:
- travis_retry pip install pytest coverage flake8 pytest-cov pytest-flake8
- travis_retry pip install --upgrade pytest
- travis_retry python setup.py install

script:
  py.test --cov=twempest --cov=tests --cov-report=term-missing --cov-fail-under=80 --flake8 twempest tests

after_success:
- bash <(curl -s https://codecov.io/bash)
